// Code generated by protoc-gen-go. DO NOT EDIT.
// source: svcdef.proto

package svcdef

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SearchRequest_Corpus int32

const (
	SearchRequest_UNIVERSAL SearchRequest_Corpus = 0
	SearchRequest_WEB       SearchRequest_Corpus = 1
	SearchRequest_IMAGES    SearchRequest_Corpus = 2
	SearchRequest_LOCAL     SearchRequest_Corpus = 3
	SearchRequest_NEWS      SearchRequest_Corpus = 4
	SearchRequest_PRODUCTS  SearchRequest_Corpus = 5
	SearchRequest_VIDEO     SearchRequest_Corpus = 6
)

var SearchRequest_Corpus_name = map[int32]string{
	0: "UNIVERSAL",
	1: "WEB",
	2: "IMAGES",
	3: "LOCAL",
	4: "NEWS",
	5: "PRODUCTS",
	6: "VIDEO",
}

var SearchRequest_Corpus_value = map[string]int32{
	"UNIVERSAL": 0,
	"WEB":       1,
	"IMAGES":    2,
	"LOCAL":     3,
	"NEWS":      4,
	"PRODUCTS":  5,
	"VIDEO":     6,
}

func (x SearchRequest_Corpus) String() string {
	return proto.EnumName(SearchRequest_Corpus_name, int32(x))
}

func (SearchRequest_Corpus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8b9c1fef3179a977, []int{0, 0}
}

type SearchRequest struct {
	Query                string               `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	PageNumber           int32                `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	ResultPerPage        int32                `protobuf:"varint,3,opt,name=result_per_page,json=resultPerPage,proto3" json:"result_per_page,omitempty"`
	Corpus               SearchRequest_Corpus `protobuf:"varint,4,opt,name=corpus,proto3,enum=SearchRequest_Corpus" json:"corpus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b9c1fef3179a977, []int{0}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *SearchRequest) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *SearchRequest) GetResultPerPage() int32 {
	if m != nil {
		return m.ResultPerPage
	}
	return 0
}

func (m *SearchRequest) GetCorpus() SearchRequest_Corpus {
	if m != nil {
		return m.Corpus
	}
	return SearchRequest_UNIVERSAL
}

type SearchResponse struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b9c1fef3179a977, []int{1}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func init() {
	proto.RegisterEnum("SearchRequest_Corpus", SearchRequest_Corpus_name, SearchRequest_Corpus_value)
	proto.RegisterType((*SearchRequest)(nil), "SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "SearchResponse")
}

func init() { proto.RegisterFile("svcdef.proto", fileDescriptor_8b9c1fef3179a977) }

var fileDescriptor_8b9c1fef3179a977 = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xcf, 0x4f, 0xfa, 0x40,
	0x10, 0xc5, 0xbf, 0x0b, 0x74, 0xbf, 0x30, 0xf2, 0x63, 0x33, 0xd1, 0xa4, 0xf1, 0x22, 0xe1, 0x40,
	0xf0, 0x60, 0x0f, 0x78, 0xf3, 0x86, 0xd0, 0x18, 0x12, 0xa4, 0xcd, 0xae, 0x40, 0xe2, 0xa5, 0x29,
	0x75, 0x44, 0x13, 0xa5, 0x65, 0xb7, 0x25, 0xf1, 0x4f, 0xf7, 0x66, 0xda, 0xca, 0xa1, 0x89, 0xc7,
	0xf9, 0xbc, 0x97, 0x79, 0x33, 0x0f, 0xda, 0xe6, 0x18, 0xbd, 0xd0, 0xab, 0x93, 0xe8, 0x38, 0x8d,
	0x07, 0xdf, 0x0c, 0x3a, 0x8a, 0x42, 0x1d, 0xbd, 0x49, 0x3a, 0x64, 0x64, 0x52, 0x3c, 0x07, 0xeb,
	0x90, 0x91, 0xfe, 0xb2, 0x59, 0x9f, 0x8d, 0x5a, 0xb2, 0x1c, 0xf0, 0x0a, 0xce, 0x92, 0x70, 0x47,
	0xc1, 0x3e, 0xfb, 0xdc, 0x92, 0xb6, 0x6b, 0x7d, 0x36, 0xb2, 0x24, 0xe4, 0x68, 0x59, 0x10, 0x1c,
	0x42, 0x4f, 0x93, 0xc9, 0x3e, 0xd2, 0x20, 0x21, 0x1d, 0xe4, 0x82, 0x5d, 0x2f, 0x4c, 0x9d, 0x12,
	0xfb, 0xa4, 0xfd, 0x70, 0x47, 0x78, 0x03, 0x3c, 0x8a, 0x75, 0x92, 0x19, 0xbb, 0xd1, 0x67, 0xa3,
	0xee, 0xf8, 0xc2, 0xa9, 0xc4, 0x3b, 0xd3, 0x42, 0x94, 0xbf, 0xa6, 0xc1, 0x33, 0xf0, 0x92, 0x60,
	0x07, 0x5a, 0xab, 0xe5, 0x7c, 0xed, 0x4a, 0x35, 0x59, 0x88, 0x7f, 0xf8, 0x1f, 0xea, 0x1b, 0xf7,
	0x5e, 0x30, 0x04, 0xe0, 0xf3, 0xc7, 0xc9, 0x83, 0xab, 0x44, 0x0d, 0x5b, 0x60, 0x2d, 0xbc, 0xe9,
	0x64, 0x21, 0xea, 0xd8, 0x84, 0xc6, 0xd2, 0xdd, 0x28, 0xd1, 0xc0, 0x36, 0x34, 0x7d, 0xe9, 0xcd,
	0x56, 0xd3, 0x27, 0x25, 0xac, 0xdc, 0xb2, 0x9e, 0xcf, 0x5c, 0x4f, 0xf0, 0xc1, 0x10, 0xba, 0xa7,
	0x6c, 0x93, 0xc4, 0x7b, 0x43, 0x7f, 0xff, 0x3e, 0xbe, 0x3b, 0x55, 0xa4, 0x48, 0x1f, 0xdf, 0x23,
	0xc2, 0x6b, 0xe0, 0x25, 0xc0, 0x6e, 0xf5, 0xfa, 0xcb, 0x9e, 0x53, 0xdd, 0xb8, 0xe5, 0x45, 0xcd,
	0xb7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x97, 0x10, 0x8b, 0xf6, 0x76, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SearchServiceClient is the client API for SearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SearchServiceClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type searchServiceClient struct {
	cc *grpc.ClientConn
}

func NewSearchServiceClient(cc *grpc.ClientConn) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/SearchService/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServiceServer is the server API for SearchService service.
type SearchServiceServer interface {
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
}

func RegisterSearchServiceServer(s *grpc.Server, srv SearchServiceServer) {
	s.RegisterService(&_SearchService_serviceDesc, srv)
}

func _SearchService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SearchService/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SearchService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _SearchService_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "svcdef.proto",
}
